// Code generated by "stringer -type=Cell"; DO NOT EDIT.

package life

import "strconv"

const _Cell_name = "DeadAlive"

var _Cell_index = [...]uint8{0, 4, 9}

func (i Cell) String() string {
	if i < 0 || i >= Cell(len(_Cell_index)-1) {
		return "Cell(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Cell_name[_Cell_index[i]:_Cell_index[i+1]]
}
